services:
  - type: web
    name: kinexis-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true